################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
    COMPOSER_MEMORY_LIMIT:        -1
    SYMFONY_DEPRECATIONS_HELPER:  disabled

################################################################
# Defined Pipeline Stages
stages:
  - quality
  - functional
  - deploy

################################################################
# Base Job
################################################################

.base:    &base
    tags:
        - Dedicated
    before_script:
        ################################################################################
        # Install Symfony
        - composer update
    after_script:
        ################################################################################
        # Run After Script
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh


################################################################
# Quality Tests
################################################################

.quality_tests:    &quality_tests
    <<: *base
    stage:      quality
    ################################################################################
    # Run Test Script
    script:
        # Execute Grumphp Testsuite
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
      # Execute Grumphp Testsuite
        - wall-e grumphp:quality
        - wall-e grumphp:stan

quality:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *quality_tests

quality:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *quality_tests

################################################################
# Functional Tests
################################################################

functional:
    image:      docker:stable
    stage:      functional
    retry:      2
    tags:
        - Dedicated
    services:
        - docker:dind
    ################################################################################
    # Install & Configure Environment
    before_script:
        # Install Git, Bash, Curl & Docker Compose
        - apk add --no-cache curl bash git docker-compose
        # Install & Build Docker Compose
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/toolkit/build.sh  | bash
    ################################################################################
    # Run Test Script
    script:
        # Wait for container to Start
        - sleep 10
        - docker-compose exec -T toolkit curl http://toolkit/
        # Execute PhpUnit Tests
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/toolkit/phpunit.sh  | bash
        # Build Splash Manifest
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/toolkit/manifest.sh  | bash
        - docker-compose exec -T toolkit ls -l

    ################################################################################
    # Run After Script
    after_script:
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/toolkit/after.sh  | bash
    artifacts:
        paths:
            - logs
            - manifest

################################################################
# Build Documentation
################################################################
pages:
    image:      jekyll/minimal:latest
    stage:      deploy
    tags:       [ Dedicated ]
    ################################################################################
    # Run Test Script
    script:
        - wget -qO - https://gitlab.com/badpixxel-robo/jekyll/-/raw/main/scripts/gitlab-pages.sh | sh
    artifacts:
        paths:
            - public
