
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache:
#        enabled: false
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Available Connector Connections
################################################################################    

    connections:

        ########################################################################
        # Flat Local File Connector
        flat-local:
            id:                 ThisIsFlatLocalWsId
            key:                ThisIsNotASecretKeyForFlatLocal
            name:               Serveur 1 (Flat Local)
            connector:          flat
            config:
                Objects:
                    Basic:
                        targets:
                            file:///app/connectors/Flat/Resources/samples/Basic/basic.json: auto
                        model:  Splash\Connectors\Flat\OpenApi\Models\Samples\Basic
                        ttl:    "-1 hour"

        ########################################################################
        # Flat Http File Connector
        flat-http:
            id:                 ThisIsFlatHttpWsId
            key:                ThisIsNotASecretKeyForFlatHttp
            name:               Serveur 2 (Flat Http)
            connector:          flat
            config:
                Objects:
                    Basic:
                        targets:
                            http://flat-http/Basic/basic.json: auto
                        model:  Splash\Connectors\Flat\OpenApi\Models\Samples\Basic
                        ttl:    "-1 hour"

        ########################################################################
        # Flat Ftp File Connector
        flat-ftp:
            id:                 ThisIsFlatFtpWsId
            key:                ThisIsNotASecretKeyForFlatFtp
            name:               Serveur 3 (Flat Ftp)
            connector:          flat
            config:
                Objects:
                    Basic:
                        targets:
                            ftp://admin:p@ssword@flat-ftp/Basic/basic.json: auto
                        model:  Splash\Connectors\Flat\OpenApi\Models\Samples\Basic
                        ttl:    "-1 hour"

        ########################################################################
        # Flat Sftp File Connector
        flat-sftp:
            id:                 ThisIsFlatSftpWsId
            key:                ThisIsNotASecretKeyForSflatFtp
            name:               Serveur 4 (Flat Sftp)
            connector:          flat
            config:
                Objects:
                    Basic:
                        targets:
                            sftp://admin:p@ssword@flat-sftp/Basic/basic.json: auto
                        model:  Splash\Connectors\Flat\OpenApi\Models\Samples\Basic
                        ttl:    "-1 hour"